### ISSUE TITLE
Can you give us a Docker compose example?

### ISSUE THREAD

**Issue by bknowles** [czerwonk/junos_exporter#275]
In your documentation, you show us the `docker run` version of how to start the JunOS Exporter.

Can you give us a sample `docker-compose.yml` entry that would work to replicate the same functionality?

Where should we put the configuration file within the docker image?  Should it be at `/config.yml`, or could we instead choose to put it at `/etc/junos_exporter/config.yml`, or somesuch?

I'm struggling to get the docker image loaded via our `docker-compose.yml` file, and so an example of how it should work would be very helpful.

Thanks!

**Comment by bknowles** [comment]
FYI, here's what I'm trying to use in our `docker-compose.yml`, which is not working:
```
  junos:
    image: czerwonk/junos_exporter
    volumes:
      - ./config/prometheus/junos_exporter_config.yml:/config.yml
    command:
      - '--config.file=/config.yml'
      - '--log.level=debug'
    ports:
      - 9326:9326
    restart: always
```

But whenever I restart docker, all the other containers restart fine, but this one container fails to load, with the error:
```
Error response from daemon: failed to create task for container: failed to create shim task:
OCI runtime create failed: runc create failed: unable to start container process:
exec: "--config.file=/config.yml": stat --config.file=/config.yml: no such file or directory: unknown
```

I've used exactly that same formatting and logic with multiple other containers, and they work fine and they copy their local configuration file into the specified location inside the container.  But that method doesn't work for this container.

**Comment by bknowles** [comment]
One of my co-workers did some testing, and found an alternate `docker-compose.yml` configuration that does seem to work:
```
  junos-exporter:
    image: czerwonk/junos_exporter
    restart: unless-stopped
    ports:
      - "9326:9326"
    volumes:
      - ./config/prometheus/junos_exporter_config.yml:/config.yml:ro
    environment:
      - CONFIG_FILE=/config.yml
```
