### ISSUE TITLE
Interface speed missing docker

### ISSUE THREAD

**Issue by AngelFreak** [czerwonk/junos_exporter#45]
So i run junos_exporter in docker, but i do not get the interface speed from my Juniper EX2300 switches.

Am i missing something ?

My config.yml
```
targets:
 -

features:
  environment: true
  bgp: false
  ospf: false
  isis: false
  nat: false
  l2circuit: true
  ldp: true
  routes: true
  routing_engine: true
  interfaces: true
  interface_diagnostic: true
  storage: true
```
