### ISSUE TITLE
No storage metrics from EX2300

### ISSUE THREAD

**Issue by AngelFreak** [czerwonk/junos_exporter#80]
I don't get any storage metrics from our Juniper EX2300-48P and EX2300-24T

There is nothing obvious in the log, and i get the other metrics just fine.
Im running junos_exporter Version: 0.9.5.

I have the feature enabled i the config:
```
features:
  environment: true
  bgp: false
  ospf: false
  isis: false
  nat: false
  l2circuit: true
  ldp: true
  routes: true
  routing_engine: true
  interfaces: true
  interface_diagnostic: true
  storage: true
  fpc: true
```
